@startwbs
'https://plantuml.com/wbs-diagram
+ Приемка и хранение сырья и полуфабрикатов
++ Склад
++- Обработка сырья. хранение полуфабрикатов
++++ Мясо-рыбный цех
++++< Овощной цех
+++- Тепловая обработка, доведение до готовности
+++++ Горячий цех
+++++< Холодный цех
+++++ Приготовление блюд и изделий
++++++ Раздача
+++++++ Порционирование, оформление и реализация
@endwbs
